info:
  name: getVehiculeConfigFilterCode
  type: http
  seq: 1

http:
  method: GET
  url: "{{gcp-dev}}/tms-cap-fleetmanagement/vehicle-configurations?isArticulated=true"
  params:
    - name: isArticulated
      value: "true"
      type: query
    - name: code
      value: B2
      type: query
      disabled: true
  body:
    type: json
    data: ""
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
