info:
  name: satVerifyConfig
  type: http
  seq: 1

http:
  method: POST
  url: "{{gcp-dev}}/tms-proc-fleetmanagement/vehicle-configurations"
  body:
    type: json
    data: "{\r

      \  \"vehicleId\": 2,\r

      \  \"containers\": [\r

      \    1,\r

      \    2\r

      \  ]\r

      }"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
